### ISSUE TITLE
I have a suggestion.

### ISSUE THREAD

**Issue by dexiaoly** [inventare/django-image-uploader-widget#110]
It would be great if you could add a drag and drop image sorting feature!
One more question, is it possible to have multiple selections of images to upload? Instead of a single upload.

**Comment by EduardoJM** [comment]
> It would be great if you could add a drag and drop image sorting feature! 

Is really a good suggestion to the admin inline feature, i will think to work on it

> One more question, is it possible to have multiple selections of images to upload? Instead of a single upload.

Using the django-admin inline is possible to make multiple files upload using this:

https://inventare.github.io/django-image-uploader-widget/docs/inline_admin/tutorial/#using-the-inline-editor

For use outside of admin, i have created an issue #98, but i don't found a good solution for now

**Comment by EduardoJM** [comment]
Moved to #139 issue.

---

The multiple images upload use outside of admin is not planned to be supported for now.

**Comment by EduardoJM** [comment]
> The multiple images upload use outside of admin is not planned to be supported for now.

For `PostgreSQL` is possible to use the `ArrayField` support:

https://inventare.github.io/django-image-uploader-widget/array_field/tutorial/
