### ISSUE TITLE
Possible to use on page with several forms?

### ISSUE THREAD

**Issue by tlcaputi** [inventare/django-image-uploader-widget#112]
Hi, Thanks for your great package! Is it possible to use this on a page with several forms? From what I can tell, the JS only looks for one editor. Thanks!

**Comment by EduardoJM** [comment]
> Hi, Thanks for your great package! Is it possible to use this on a page with several forms? From what I can tell, the JS only looks for one editor. Thanks!

Thanks for your questions. Yes, is possible to use with multiple forms. The JS code has an function `initializeWidgets(element)` [L233](https://github.com/inventare/django-image-uploader-widget/blob/main/image_uploader_widget/static/admin/js/image-uploader-widget.js#L233) to initialize all widgets inside an element. This function is called on the `DOMContentLoaded` event with `document` [L240](https://github.com/inventare/django-image-uploader-widget/blob/main/image_uploader_widget/static/admin/js/image-uploader-widget.js#L240).

Inside the `django-admin` the widget is started too inside the inlines `formset:added` event [L245](https://github.com/inventare/django-image-uploader-widget/blob/main/image_uploader_widget/static/admin/js/image-uploader-widget.js#L245).

**Comment by EduardoJM** [comment]
Documented this into our docs at: https://inventare.github.io/django-image-uploader-widget/docs/widget/multiple-instances-of-same-form/

---

Closing this issue, if you have any other problem, can reply or open a new =)
