### ISSUE TITLE
Add array field widget

### ISSUE THREAD

**Issue by lyf2000** [inventare/django-image-uploader-widget#146]
I propose to create html for rendering image sequence to model's ArrayField(ImageField)

**Comment by EduardoJM** [comment]
I never used `ArrayField` in any of projects that i'm worked.

But i can study about it on the next week and verify the possibility of use this widget with ArrayField

**Comment by EduardoJM** [comment]
Updates:

The `ArrayField` not works property with `ImageField`. The files is not saved correctly to system. Currently i'm working on a extension of ArrayField to support it.

**Comment by EduardoJM** [comment]
Released at 0.5.0 on PyPI. The basic usage documentation:

https://inventare.github.io/django-image-uploader-widget/array_field/tutorial/
