### ISSUE TITLE
Issue working with crispy forms?

### ISSUE THREAD

**Issue by arunk** [inventare/django-image-uploader-widget#203]
I'm trying your uploader widget in a form, but couldn't get it to display. No matter what I did, it seemed to show the default FileUpload widget. Then I started debugging the issue one at a time, and finally when I stopped using `{% crispy form %}` to display the form and instead used `{{ form.as_p }}` to display it, your widget worked. Is there anything in particular about your widget that might not make it work with [crispy forms](https://django-crispy-forms.readthedocs.io/en/latest/)? I am using a few custom widgets with the crispy library and have not had any issues. I will raise the issue in the crispy library github repo as well. Do let me know if you need any logging information or anything else about my current configuration.

My environment:
Python 3.12
Django 4.2.16
Latest version of django-image-uploader-widget==1.0.0

**Comment by arunk** [comment]
Just as a follow up turns out crispy forms does require some special things for custom widgets. But everything I have done in my custom widget, is there in your custom widget as well. So I'm not sure why it isn't working. I will raise the issue on crispy-forms repo as well. here is the [docs for crispy-forms](https://django-crispy-forms.readthedocs.io/en/latest/faq.html#using-a-custom-widget)

**Comment by EduardoJM** [comment]
Well, really i never tested this widget with crispy forms, and this is a good time for add a native support for it. I will work on this issue for next weeks.

**Comment by arunk** [comment]
hey thanks so much for this! i was looking at a similar approach, defining a custom template within crispy FormHelper.
