### ISSUE TITLE
upload images with ArrayField

### ISSUE THREAD

**Issue by nekodevjp** [inventare/django-image-uploader-widget#205]
Hello, congratulations on the work of this beautiful image upload for Django.

I'm using ArrayField to upload more than one image, but it is allowing upload of other formats. I checked the documentation, but I couldn't implement it for ArrayField following the guidance of Widget and Inline Admin.

![image](https://github.com/user-attachments/assets/6ac43691-5ece-4d0d-b610-33ad791630ef)

**Comment by EduardoJM** [comment]
Hello, Thanks =)

This is a known issue, related on discussion #198 and on issue #199. I will close the #199 because here is better described and in this week i will work on this issue.

**Comment by EduardoJM** [comment]
@nekodevjp the fix was released into 1.0.1 version at PyPI.

**Comment by nekodevjp** [comment]
@EduardoJM . After you fixed the accept for the ArrayField in forms.py, the error you described [here](https://inventare.github.io/django-image-uploader-widget/array_field/02-prevent-raw-change/) is occurring.
