### ISSUE TITLE
images field coming as None (ArrayField)

### ISSUE THREAD

**Issue by nekodevjp** [inventare/django-image-uploader-widget#210]
After you fixed the accept for the ArrayField, the error you described [here](https://inventare.github.io/django-image-uploader-widget/array_field/02-prevent-raw-change/) is occurring. It's like the images field is coming as None. And returns this error:

'NoneType' object has no attribute 'name'

I tested the lib in the previous version (django-image-uploader-widget==1.0.0) and it worked.

**Comment by nekodevjp** [comment]
I checked further and discovered that the error occurs due to the lack of enctype="multipart/form-data" in the <form>.

It would be good to include this guidance in the documentation :)

<form method="post" enctype="multipart/form-data">

**Comment by EduardoJM** [comment]
> I checked further and discovered that the error occurs due to the lack of enctype="multipart/form-data" in the `<form>`
> 
> It would be good to include this guidance in the documentation :)
> 
> `<form method="post" enctype="multipart/form-data">`

This behaviour is descibed in [django documentation](https://docs.djangoproject.com/en/5.1/topics/http/file-uploads/#basic-file-uploads).
