### ISSUE TITLE
JS error with  inline and doesn't open the file upload

### ISSUE THREAD

**Issue by marlonleite** [inventare/django-image-uploader-widget#47]
[https://i.ibb.co/G5Qcx0h/Captura-de-Tela-2022-08-30-a-s-19-04-09.png](https://i.ibb.co/G5Qcx0h/Captura-de-Tela-2022-08-30-a-s-19-04-09.png)

An error doesn't let open the file upload when trying the first time open from an inline formset. Something in javascript.

django 4.1 / using forms with ImageUploaderWidget

**Comment by EduardoJM** [comment]
Well, i will investigate this tonight to made an fix for that.

Thanks for notify that problem.

**Comment by EduardoJM** [comment]
The problem is in the formset:added event (apparently the django changed the mode of sending the event arguments), currently i go to add an "workaround" into the project to get the row to the formset:added event by another way if the element is undefined (print error).

**Comment by EduardoJM** [comment]
Released a fix into 0.1.7 at Github and PyPi, please test if that really solved the problem @marlonleite

**Comment by marlonleite** [comment]
cool @EduardoJM  everything working now. Thank you :)
